### ISSUE TITLE
Sanity Check: Should be possible to do this and get a cert signed by a commercial CA?

### ISSUE THREAD

**Issue by ckcr4lyf** [salrashid123/kms_golang_signer#1]
Sorry, issue is a bit inappropriate, but this repo did not have discussions enabled.

This project is quite interesting, but I just wanted to sanity check one thing: Technically, if the RSA Private Key material is hidden in KMS, but KMS API offers a signing operations, we can generate a CSR (which you have an example for as well), and get it signed by a commercial CA such as Verisign or Comodo, correct?

To them it does not matter what our Private Key interface is (e.g. it could be an HSM), as long as we signed the CSR correctly.

I ask this be cause I need to perform mTLS with a party which requires certs signed  by certain CAs, and this would be more secure than the application logic having access to the raw RSA Private Key.

**Comment by salrashid123** [comment]
sure, a signing CA would not care how the  the private key is stored  (it can be on file, on kms on hardware , etc).

the  csr  includes the public key and a signature using the private key and the issuing ca is oblivous about the storage details.

---

kms based tls demo here is just a demo (i haven't directly heard of this use  before and just wrote this repo for fun).

note that each tls connection would require an KMS api call (eg, added latency and costs for that operation0





* https://blog.salrashid.dev/en/articles/2021/nginx_with_tpm_ssl/
* https://github.com/salrashid123/go_tpm_https_embed
* https://github.com/salrashid123/mtls_pkcs11
